"""add code_path to products and genut_instances

Revision ID: 38fc35ad54d5
Revises: f944f16d574a
Create Date: 2026-06-16 15:15:53.999048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38fc35ad54d5'
down_revision: Union[str, Sequence[str], None] = 'f944f16d574a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genut_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_path', sa.String(length=1024), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_path', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('code_path')

    with op.batch_alter_table('genut_instances', schema=None) as batch_op:
        batch_op.drop_column('code_path')

    # ### end Alembic commands ###
