"""add assure_repo_url to genut_instances

Revision ID: 406e1798f687
Revises: fe55b4bebf19
Create Date: 2026-06-17 16:41:32.301125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406e1798f687'
down_revision: Union[str, Sequence[str], None] = 'fe55b4bebf19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genut_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assure_repo_url', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genut_instances', schema=None) as batch_op:
        batch_op.drop_column('assure_repo_url')

    # ### end Alembic commands ###
