"""Add git_update_mode to products

Revision ID: 6923b5a90d26
Revises: e2b8f04c7a19
Create Date: 2026-07-19 11:34:52.521607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6923b5a90d26'
down_revision: Union[str, Sequence[str], None] = 'e2b8f04c7a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('git_update_mode', sa.String(length=16), server_default='reset', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('git_update_mode')

    # ### end Alembic commands ###
