"""add auto-run product fields

Revision ID: 8fbadfbbd173
Revises: e6c17f5ef2fa
Create Date: 2026-06-30 18:13:50.016708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbadfbbd173'
down_revision: Union[str, Sequence[str], None] = 'e6c17f5ef2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 행 백필을 위해 NOT NULL 컬럼엔 server_default를 둔다(신규 행은 ORM 기본값 사용).
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('auto_run', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('auto_interval_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('auto_file_list', sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )
        batch_op.add_column(sa.Column('cmake_template', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('cmake_template')
        batch_op.drop_column('auto_file_list')
        batch_op.drop_column('auto_interval_seconds')
        batch_op.drop_column('auto_run')

    # ### end Alembic commands ###
