"""Add product_test_files table

Revision ID: a04dc0b5b0af
Revises: 20e9e4efaf2c
Create Date: 2026-06-23 15:59:54.403685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04dc0b5b0af'
down_revision: Union[str, Sequence[str], None] = '20e9e4efaf2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_test_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('rel_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name', 'rel_path', name='uq_product_test_file')
    )
    with op.batch_alter_table('product_test_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_test_files_product_name'), ['product_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_test_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_test_files_product_name'))

    op.drop_table('product_test_files')
    # ### end Alembic commands ###
