"""add test_status_snapshots table

Revision ID: b069b8e28222
Revises: 4f8e02b6d1c7
Create Date: 2026-07-07 17:45:30.215406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b069b8e28222'
down_revision: Union[str, Sequence[str], None] = '4f8e02b6d1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_status_snapshots',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=2048), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_status_snapshots')
    # ### end Alembic commands ###
