"""Drop product_test_files, add products.exclude_globs

Revision ID: e6c17f5ef2fa
Revises: a04dc0b5b0af
Create Date: 2026-06-26 15:34:41.652547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c17f5ef2fa'
down_revision: Union[str, Sequence[str], None] = 'a04dc0b5b0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_test_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_test_files_product_name'))

    op.drop_table('product_test_files')
    # 기존 행을 위해 server_default '[]'를 둔다(빈 목록). 모델 기본값(default=list)은 신규 ORM 객체용.
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('exclude_globs', sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('exclude_globs')

    op.create_table('product_test_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('rel_path', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name', 'rel_path', name=op.f('uq_product_test_file'))
    )
    with op.batch_alter_table('product_test_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_test_files_product_name'), ['product_name'], unique=False)

    # ### end Alembic commands ###
