"""add ds_assist_user_id to genut_instances

Revision ID: fe55b4bebf19
Revises: 38fc35ad54d5
Create Date: 2026-06-16 17:38:36.907314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe55b4bebf19'
down_revision: Union[str, Sequence[str], None] = '38fc35ad54d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genut_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ds_assist_user_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genut_instances', schema=None) as batch_op:
        batch_op.drop_column('ds_assist_user_id')

    # ### end Alembic commands ###
